version: "3.8"
services:
  api:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    build: ./backend
    command: celery -A worker.celery_app worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
