[build]
builder = "DOCKERFILE"
dockerfilePath = ".railway/Dockerfile"

[build.buildArgs]
GDRIVE_FILE_ID = "${{GDRIVE_FILE_ID}}"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
